# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be349a73b59cf6dcb5aeaedbb62561631f46940a738f93a4201ce2714db6d876ff9d2762dbe187802c99c9968dc8d8513ce85bcbdd2d724531ee47eae817af36

test:
  secret_key_base: b5f35c57c0227ff0f0a33b2c148c52b97dcfd9529db58c55371b1be8af14775187bd1373cc2410001da129e4eb05963b1f7ec0963eee57c6a65bd565dd8f8e34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
